get http://localhost:8000/api/users/

###
post http://localhost:8000/api/users/
content-type: application/json

    {
        "id": "",
        "name": "John",
        "password": "4242525"
    }

###
put http://localhost:8000/api/users/2
content-type: application/json

{
  "name": {
    "first_name": "Thiago",
    "about_name": "Manuel Lima"
  },
  "email": "erick_manuel_lima@india.com",
  "phone_number": "(27) 98613-1255",
  "cpf": "051.610.742-99",
  "birthday": "05/03/1976",
  "password": "hBga3BdYKH"
}

###

DELETE http://localhost:8000/api/users/4
